-- O seed de desenvolvimento insere ids explicitos (tb_endereco 1 e 2, tb_condominio 1 e 2).
-- Em coluna GENERATED BY DEFAULT AS IDENTITY isso NAO avanca a sequencia: ela continua em 1,
-- e o primeiro registro criado pela aplicacao colide com o seed
-- ("duplicate key value violates unique constraint").
--
-- Realinha cada sequencia com o maior id ja gravado. Idempotente: rodar de novo com a
-- sequencia ja correta nao muda nada.

DO $$
DECLARE
    tabela  TEXT;
    coluna  TEXT;
    seq     TEXT;
    maximo  BIGINT;
BEGIN
    FOR tabela, coluna IN
        SELECT * FROM (VALUES
            ('tb_endereco',    'id_endereco'),
            ('tb_condominio',  'id_condominio'),
            ('tb_unidade',     'id_unidade'),
            ('tb_pessoa',      'id_pessoa'),
            ('tb_taxa_extra',  'id_taxa_extra'),
            ('tb_meio_contato','id_meio_contato')
        ) AS t (tabela, coluna)
    LOOP
        seq := pg_get_serial_sequence(tabela, coluna);
        CONTINUE WHEN seq IS NULL;

        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I', coluna, tabela) INTO maximo;
        -- is_called = false quando a tabela esta vazia, para o proximo id ser 1 e nao 2.
        PERFORM setval(seq, GREATEST(maximo, 1), maximo > 0);
    END LOOP;
END $$;
