-- Recria o schema atual, exatamente como o Hibernate infere hoje a partir das
-- entidades de domínio (Condominio, Endereco, Pessoa, TaxaExtra, MeioContato).
-- Nenhuma alteração de modelo de dados foi feita aqui, apenas a materialização
-- via migration versionada (Flyway passa a ser o dono do schema;
-- hibernate.ddl-auto=validate a partir de agora).

CREATE TABLE tb_endereco (
    id_endereco     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_cep          BIGINT,
    ds_endereco     VARCHAR(255),
    ds_complemento  VARCHAR(255)
);

CREATE TABLE tb_condominio (
    id_condominio       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_ddd              BIGINT,
    nr_telefone         BIGINT,
    vl_taxa             DOUBLE PRECISION,
    id_endereco         BIGINT NOT NULL,
    vl_juros            DOUBLE PRECISION,
    vl_multa            DOUBLE PRECISION,
    in_taxa_extra       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_condominio_endereco UNIQUE (id_endereco),
    CONSTRAINT fk_condominio_endereco FOREIGN KEY (id_endereco) REFERENCES tb_endereco (id_endereco)
);

CREATE TABLE tb_pessoa (
    id_pessoa           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ds_pessoa            VARCHAR(255),
    nr_unidade           BIGINT,
    nr_cpf               VARCHAR(255),
    in_envio_email       BOOLEAN DEFAULT FALSE,
    in_envio_impresso    BOOLEAN DEFAULT FALSE,
    in_sindico           BOOLEAN DEFAULT FALSE,
    id_condominio        BIGINT NOT NULL,
    id_endereco          BIGINT NOT NULL,
    CONSTRAINT uk_pessoa_condominio UNIQUE (id_condominio),
    CONSTRAINT uk_pessoa_endereco UNIQUE (id_endereco),
    CONSTRAINT fk_pessoa_condominio FOREIGN KEY (id_condominio) REFERENCES tb_condominio (id_condominio),
    CONSTRAINT fk_pessoa_endereco FOREIGN KEY (id_endereco) REFERENCES tb_endereco (id_endereco)
);

CREATE TABLE tb_taxa_extra (
    id_taxa_extra    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_condominio    BIGINT NOT NULL,
    vl_taxa_extra    DOUBLE PRECISION,
    nr_parcelas      INTEGER,
    ds_taxa_extra    VARCHAR(255),
    dt_cadastro      TIMESTAMP,
    CONSTRAINT fk_taxa_extra_condominio FOREIGN KEY (id_condominio) REFERENCES tb_condominio (id_condominio)
);

CREATE TABLE tb_meio_contato (
    id_meio_contato        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa              BIGINT NOT NULL,
    cd_tipo_meio_contato   VARCHAR(5) NOT NULL,
    ds_identificacao       VARCHAR(255),
    CONSTRAINT fk_meio_contato_pessoa FOREIGN KEY (id_pessoa) REFERENCES tb_pessoa (id_pessoa)
);
