-- Controle mensal de cobrança da taxa ordinária, por unidade. Vinculado à Unidade, nunca à
-- Pessoa: troca de morador não afeta o histórico de pagamento da unidade.

ALTER TABLE tb_condominio ADD COLUMN nr_dia_vencimento_taxa_ordinaria INTEGER;

CREATE TABLE tb_cobranca_ordinaria (
    id_cobranca_ordinaria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidade            BIGINT NOT NULL REFERENCES tb_unidade (id_unidade),
    dt_competencia        DATE NOT NULL,
    dt_vencimento         DATE NOT NULL,
    vl_cobranca           DOUBLE PRECISION,
    ds_pix_copia_cola     TEXT,
    ds_linha_digitavel    VARCHAR(100),
    dt_pagamento          DATE,
    dt_cadastro           TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_cobranca_unidade_competencia UNIQUE (id_unidade, dt_competencia)
);
